name: CI
on:
  push:
    branches:
      - master
    tags:
      - "!*"
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          concurrency=$(sysctl -n hw.ncpu)
          cat Labels.txt | xargs -L1 -P${concurrency} -I{} zsh -c "./Installomator.sh {} 2>&1 | while read -r line; do echo \"{}:\$line:\"; done || exit 255"
