name: CI
on:
  push:
    branches:
      - master
    tags:
      - "!*"
  pull_request:

jobs:
  collect-labels:
    runs-on: macos-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          labelsJSON=$(jq -R -s -c 'split("\n")' < Labels.txt | jq '[.[] | select(. != "")] | @json')
          echo "::set-output name=matrix::${labelsJSON}"

  build:
    needs: collect-labels
    runs-on: macos-latest
    strategy:
      matrix:
        label: ${{ fromJson(needs.collect-labels.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          ./Installomator.sh "${{ matrix.label }}"
